name: Draft PDF

on:
  push:
    paths:
      - joss.md
      - .github/workflows/draft-pdf.yml

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper-path: joss.md
          output-path: joss.pdf  # Force the output to this file

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: joss-pdf
          path: joss.pdf  # Matches the output-path above

      - name: Commit PDF to repository
        uses: EndBug/add-and-commit@v9
        with:
          message: "(auto) add paper draft"
          add: "joss.pdf"
